---
version: 1
disable_existing_loggers: False

# Define format of output logs (named 'simple').
formatters:
  simple:
    format: "%(asctime)s %(levelname)-5s [%(threadName)s] %(name)s->%(funcName)s<%(lineno)d>  %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  # Create rotating file handler using 'simple' format.
  file_handler:
      #class: logging.handlers.RotatingFileHandler
      #maxBytes: 10485760  # 10MB

      class: logging.handlers.TimedRotatingFileHandler
      level: DEBUG
      formatter: simple
      when: 'midnight'
      backupCount: 32
      encoding: utf8
      filename: ..\..\logs\infinite.log

loggers:
  schedule:
    level: ERROR
    handlers: [console, file_handler]
    propagate: yes

  selenium:
    level: ERROR
    handlers: [console, file_handler]
    propagate: yes

  urllib3:
    level: ERROR
    handlers: [console, file_handler]
    propagate: yes

  infinite:
    level: DEBUG
    handlers: [console, file_handler]
    propagate: no

root:
  level: DEBUG
  handlers: [console, file_handler]
  propagate: no
